CREATE TABLE [lutblFrontEnd_Version] (
  [thisFEVersionNumber] VARCHAR (255) CONSTRAINT [Index_B811BF7C_C6C5_49E9] UNIQUE  CONSTRAINT [Index_DEB04D77_906D_49DF] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL 
)
